// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUVMVjxdLS5HJpf0yXhXy_3OTThwcSULc',
    appId: '1:1061164939553:web:2e407ef11e91187fb72660',
    messagingSenderId: '1061164939553',
    projectId: 'bolt-d1593',
    authDomain: 'bolt-d1593.firebaseapp.com',
    storageBucket: 'bolt-d1593.firebasestorage.app',
    measurementId: 'G-LZ8HN6C1V4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOwF-OrvYljJ7qVIb27XQVX45zmh1AYgY',
    appId: '1:1061164939553:android:779ba706eefe9b55b72660',
    messagingSenderId: '1061164939553',
    projectId: 'bolt-d1593',
    storageBucket: 'bolt-d1593.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATpKTAQQ42J-UkH3lQWK6FWNYsWg3JAko',
    appId: '1:1061164939553:ios:1da20d5a4dda95d4b72660',
    messagingSenderId: '1061164939553',
    projectId: 'bolt-d1593',
    storageBucket: 'bolt-d1593.firebasestorage.app',
    iosClientId: '1061164939553-pibmnkucu5kskjq85r7gt7bk14g5go85.apps.googleusercontent.com',
    iosBundleId: 'com.example.driversApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATpKTAQQ42J-UkH3lQWK6FWNYsWg3JAko',
    appId: '1:1061164939553:ios:1da20d5a4dda95d4b72660',
    messagingSenderId: '1061164939553',
    projectId: 'bolt-d1593',
    storageBucket: 'bolt-d1593.firebasestorage.app',
    iosClientId: '1061164939553-pibmnkucu5kskjq85r7gt7bk14g5go85.apps.googleusercontent.com',
    iosBundleId: 'com.example.driversApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUVMVjxdLS5HJpf0yXhXy_3OTThwcSULc',
    appId: '1:1061164939553:web:d2611867532d52eeb72660',
    messagingSenderId: '1061164939553',
    projectId: 'bolt-d1593',
    authDomain: 'bolt-d1593.firebaseapp.com',
    storageBucket: 'bolt-d1593.firebasestorage.app',
    measurementId: 'G-ZPHYJYVRZR',
  );
}
